# Decision Tree
medical dataset recommends drug

In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree

In [57]:
df = pd.read_csv(
    'https://icarus.cs.weber.edu/~hvalle/cs4580/data/drug200.csv')
df.to_csv('../data/drug.scv', index=False)
df.head()

Unnamed: 0  Age Sex      BP Cholesterol  Na_to_K   Drug
0           0   23   F    HIGH        HIGH   25.355  drugY
1           1   47   M     LOW        HIGH   13.093  drugC
2           2   47   M     LOW        HIGH   10.114  drugC
3           3   28   F  NORMAL        HIGH    7.798  drugX
4           4   61   F     LOW        HIGH   18.043  drugY

In [58]:
# Explore data
df.shape

(200, 7)

In [59]:
df['Drug'].value_counts()

Drug
drugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [60]:
# Our target and features
cols = df.columns.to_list()
cols.remove('Drug')
cols.remove('Unnamed: 0')
cols

['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']

In [61]:
X = df[cols].values # features matrix
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [62]:
# Modify sex column to 0/1 
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F', 'M'])
X[:, 1] = le_sex.transform(X[:, 1])

In [63]:
X[0:5]

array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.114],
       [28, 0, 'NORMAL', 'HIGH', 7.798],
       [61, 0, 'LOW', 'HIGH', 18.043]], dtype=object)

In [64]:
df['Cholesterol'].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [65]:
# Modify Cholesterol column
le_cho = preprocessing.LabelEncoder()
le_cho.fit(df['Cholesterol'].unique())
X[:, 3] = le_cho.transform(X[:, 3])

le_BP = preprocessing.LabelEncoder()
le_BP.fit(df['BP'].unique())
X[:, 2] = le_BP.transform(X[:, 2])
X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)